apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-proxy
  name: nginx-proxy
spec:
  ports:
  - name: 9090-tcp
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: nginx-proxy
  sessionAffinity: None
  type: ClusterIP
